# Generated by Django 3.0.3 on 2020-02-25 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_venda', '0002_auto_20200225_0836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendedor',
            options={'verbose_name': 'Vendedor', 'verbose_name_plural': 'Vendedores'},
        ),
    ]
