# Generated by Django 3.0.3 on 2020-02-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_venda', '0003_auto_20200225_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='Cpf'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
    ]
