# Generated by Django 3.0.3 on 2020-02-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_venda', '0004_auto_20200225_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Cpf'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='nome',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome'),
        ),
    ]
