# Generated by Django 3.0.3 on 2020-02-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_venda', '0006_auto_20200225_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='valor_venda',
            field=models.FloatField(blank=True, max_length=150, null=True, verbose_name='Valor das vendas'),
        ),
    ]
