# Generated by Django 3.0.3 on 2020-02-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_venda', '0007_auto_20200225_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='qt_hr_trabalhadas',
            field=models.IntegerField(blank=True, max_length=150, null=True, verbose_name='Quantidade de horas trabalhada'),
        ),
    ]
