# Generated by Django 3.0.3 on 2020-02-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_venda', '0008_auto_20200225_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='salario',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Salario'),
        ),
    ]
